import type { LessonContent } from '../../types'

export const lessonContents: Record<string, LessonContent> = {
  'l1-u6-l1': {
    lessonId: 'l1-u6-l1',
    durationMin: 35,
    exercises: [
      {
        type: 'explain',
        id: 'e1',
        title: 'was / were',
        points: [
          'I/he/she/it was — You/we/they were',
          "wasn't / weren't",
          'Was she at home? Were you late?',
          'yesterday, last night, last week, … ago',
        ],
        examples: [
          'I was at work yesterday.',
          'They were happy.',
          "We weren't late.",
        ],
      },
      {
        type: 'drill',
        id: 'e2',
        prompt: 'I ___ at home last night.',
        options: ['was', 'were', 'am'],
        answer: 'was',
      },
      {
        type: 'drill',
        id: 'e3',
        prompt: 'You ___ early yesterday.',
        options: ['were', 'was', 'are'],
        answer: 'were',
      },
      {
        type: 'drill',
        id: 'e4',
        prompt: 'She ___ ill last week. (отрицание)',
        options: ["wasn't", "weren't", "isn't"],
        answer: "wasn't",
      },
      {
        type: 'drill',
        id: 'e5',
        prompt: '___ you at the museum?',
        options: ['Were', 'Was', 'Are'],
        answer: 'Were',
      },
      {
        type: 'builder',
        id: 'e6',
        prompt: 'Past location',
        tokens: ['I', 'was', 'at', 'work', 'yesterday', '.'],
        answer: ['I', 'was', 'at', 'work', 'yesterday', '.'],
      },
      {
        type: 'cloze',
        id: 'e7',
        text: 'Where ___ you two hours ago? — I ___ away.',
        gaps: [
          { id: 'g1', answer: 'were', options: ['were', 'was', 'are'] },
          { id: 'g2', answer: 'was', options: ['was', 'were', 'am'] },
        ],
      },
      {
        type: 'cards',
        id: 'e8',
        cards: [
          { id: 'u6c1', term: 'yesterday', translation: 'вчера', example: 'Yesterday I was busy.' },
          { id: 'u6c2', term: 'last night', translation: 'прошлой ночью / вчера вечером', example: 'Last night I was tired.' },
          { id: 'u6c3', term: 'last week', translation: 'на прошлой неделе', example: 'Last week we were away.' },
          { id: 'u6c4', term: 'ago', translation: 'назад', example: 'Two days ago.' },
          { id: 'u6c5', term: 'ill', translation: 'больной', example: 'She was ill.' },
          { id: 'u6c6', term: 'late', translation: 'поздний / опоздавший', example: 'I was late.' },
          { id: 'u6c7', term: 'early', translation: 'ранний', example: 'We were early.' },
          { id: 'u6c8', term: 'away', translation: 'в отъезде / не на месте', example: 'He was away.' },
        ],
      },
      {
        type: 'produce',
        id: 'e9',
        prompt: 'Where were you?',
        promptRu: 'Где вы были вчера утром / днём / вечером? 5–6 предложений с was/were.',
        hints: ['Yesterday morning I was…', 'At 3 I was…', 'In the evening…'],
        minSentences: 5,
      },
    ],
  },

  'l1-u6-l2': {
    lessonId: 'l1-u6-l2',
    durationMin: 35,
    exercises: [
      {
        type: 'explain',
        id: 'e1',
        title: 'Past Simple — regular verbs',
        points: [
          'Обычные глаголы: V + -ed — worked, played, visited',
          'like → liked, stop → stopped, study → studied',
          'Форма одна для всех лиц: I/she worked',
          'Произношение: /t/ liked, /d/ played, /ɪd/ wanted — пока просто замечаем',
        ],
        examples: [
          'I worked yesterday.',
          'We visited a museum.',
          'She stayed at home.',
        ],
      },
      {
        type: 'drill',
        id: 'e2',
        prompt: 'work → ___',
        options: ['worked', 'workd', 'werken'],
        answer: 'worked',
      },
      {
        type: 'drill',
        id: 'e3',
        prompt: 'She ___ a film last night. (watch)',
        options: ['watched', 'watch', 'watches'],
        answer: 'watched',
      },
      {
        type: 'drill',
        id: 'e4',
        prompt: 'They ___ their friends. (visit)',
        options: ['visited', 'visit', 'visits'],
        answer: 'visited',
      },
      {
        type: 'drill',
        id: 'e5',
        prompt: 'I ___ at a hotel. (stay)',
        options: ['stayed', 'stay', 'stayeded'],
        answer: 'stayed',
      },
      {
        type: 'builder',
        id: 'e6',
        prompt: 'Weekend line',
        tokens: ['We', 'walked', 'in', 'the', 'park', 'and', 'cooked', 'dinner', '.'],
        answer: ['We', 'walked', 'in', 'the', 'park', 'and', 'cooked', 'dinner', '.'],
      },
      {
        type: 'cloze',
        id: 'e7',
        text: 'On Saturday I ___ my friend. We ___ about the trip and ___ a film.',
        gaps: [
          { id: 'g1', answer: 'called', options: ['called', 'call', 'calls'] },
          { id: 'g2', answer: 'talked', options: ['talked', 'talk', 'talks'] },
          { id: 'g3', answer: 'watched', options: ['watched', 'watch', 'watching'] },
        ],
      },
      {
        type: 'cards',
        id: 'e8',
        cards: [
          { id: 'u6c9', term: 'worked', translation: 'работал(а)', example: 'I worked late.' },
          { id: 'u6c10', term: 'visited', translation: 'навестил(а) / посетил(а)', example: 'We visited a museum.' },
          { id: 'u6c11', term: 'watched', translation: 'смотрел(а)', example: 'I watched a film.' },
          { id: 'u6c12', term: 'played', translation: 'играл(а)', example: 'They played tennis.' },
          { id: 'u6c13', term: 'cooked', translation: 'готовил(а)', example: 'She cooked pasta.' },
          { id: 'u6c14', term: 'stayed', translation: 'остался / остановился', example: 'I stayed at home.' },
          { id: 'u6c15', term: 'walked', translation: 'ходил(а) пешком', example: 'We walked a lot.' },
          { id: 'u6c16', term: 'called', translation: 'позвонил(а)', example: 'He called me.' },
        ],
      },
      {
        type: 'produce',
        id: 'e9',
        prompt: 'Last weekend (regular)',
        promptRu: '5–6 предложений о прошлом уикенде с правильными глаголами (-ed).',
        hints: ['I visited…', 'We walked…', 'I cooked…', 'I watched…'],
        minSentences: 5,
      },
    ],
  },

  'l1-u6-l3': {
    lessonId: 'l1-u6-l3',
    durationMin: 35,
    exercises: [
      {
        type: 'explain',
        id: 'e1',
        title: 'Past Simple — irregular verbs',
        points: [
          'Неправильные глаголы нужно запоминать: go→went, see→saw, buy→bought',
          'Утверждение: I went / she went (без -ed)',
          'Частые: went, came, had, did, saw, got, took, made, ate, drank, bought, met, said, left',
          'Вопросы и отрицания — в следующем уроке (Did…?)',
        ],
        examples: [
          'I went to the city.',
          'She bought a ticket.',
          'We met our friends.',
        ],
      },
      {
        type: 'drill',
        id: 'e2',
        prompt: 'go → ___',
        options: ['went', 'goed', 'goes'],
        answer: 'went',
      },
      {
        type: 'drill',
        id: 'e3',
        prompt: 'see → ___',
        options: ['saw', 'seed', 'seen'],
        answer: 'saw',
      },
      {
        type: 'drill',
        id: 'e4',
        prompt: 'buy → ___',
        options: ['bought', 'buyed', 'brought'],
        answer: 'bought',
      },
      {
        type: 'drill',
        id: 'e5',
        prompt: 'Yesterday I ___ lunch at 2. (have)',
        options: ['had', 'haved', 'has'],
        answer: 'had',
      },
      {
        type: 'builder',
        id: 'e6',
        prompt: 'City day',
        tokens: ['I', 'went', 'to', 'the', 'museum', 'and', 'saw', 'a', 'film', '.'],
        answer: ['I', 'went', 'to', 'the', 'museum', 'and', 'saw', 'a', 'film', '.'],
      },
      {
        type: 'cloze',
        id: 'e7',
        text: 'She ___ home late. She ___ a sandwich and ___ tea.',
        gaps: [
          { id: 'g1', answer: 'came', options: ['came', 'comed', 'come'] },
          { id: 'g2', answer: 'made', options: ['made', 'maked', 'make'] },
          { id: 'g3', answer: 'drank', options: ['drank', 'drinked', 'drunk'] },
        ],
      },
      {
        type: 'cards',
        id: 'e8',
        cards: [
          { id: 'u6c17', term: 'went', translation: 'ходил / поехал (go)', example: 'I went out.' },
          { id: 'u6c18', term: 'saw', translation: 'видел (see)', example: 'I saw a friend.' },
          { id: 'u6c19', term: 'bought', translation: 'купил (buy)', example: 'I bought a ticket.' },
          { id: 'u6c20', term: 'had', translation: 'имел / ел (have)', example: 'We had coffee.' },
          { id: 'u6c21', term: 'met', translation: 'встретил (meet)', example: 'I met Anna.' },
          { id: 'u6c22', term: 'took', translation: 'взял / доехал (take)', example: 'I took a taxi.' },
          { id: 'u6c23', term: 'ate', translation: 'ел (eat)', example: 'We ate pizza.' },
          { id: 'u6c24', term: 'left', translation: 'ушёл / уехал (leave)', example: 'He left at 6.' },
        ],
      },
      {
        type: 'produce',
        id: 'e9',
        prompt: 'Yesterday I…',
        promptRu: 'Рассказ «Yesterday I…» с ≥6 неправильными глаголами в Past.',
        hints: ['went', 'saw', 'had', 'bought', 'met', 'took', 'ate'],
        minSentences: 6,
      },
    ],
  },

  'l1-u6-l4': {
    lessonId: 'l1-u6-l4',
    durationMin: 40,
    exercises: [
      {
        type: 'explain',
        id: 'e1',
        title: 'Блок A — Past questions (Did…?)',
        points: [
          'Did you/he/she + V1? — Did you go? Did she see…?',
          "Yes, I did. / No, I didn't.",
          "Where did you go? What did you see?",
          'После did глагол без -ed и без 3 лица: Did she go? (не went / goes)',
        ],
        examples: [
          'Did you enjoy the trip?',
          "I didn't stay at home.",
          'What did you buy?',
        ],
      },
      {
        type: 'drill',
        id: 'e2',
        prompt: '___ you go to the park?',
        options: ['Did', 'Do', 'Were'],
        answer: 'Did',
      },
      {
        type: 'drill',
        id: 'e3',
        prompt: 'Where did she ___?',
        options: ['go', 'went', 'goes'],
        answer: 'go',
      },
      {
        type: 'drill',
        id: 'e4',
        prompt: 'I ___ go out yesterday. (отрицание)',
        options: ["didn't", "don't", "wasn't"],
        answer: "didn't",
      },
      {
        type: 'drill',
        id: 'e5',
        prompt: 'What ___ you buy?',
        options: ['did', 'do', 'were'],
        answer: 'did',
      },
      {
        type: 'builder',
        id: 'e6',
        prompt: 'Соберите вопрос',
        tokens: ['Did', 'you', 'enjoy', 'the', 'trip', '?'],
        answer: ['Did', 'you', 'enjoy', 'the', 'trip', '?'],
      },
      {
        type: 'explain',
        id: 'e7',
        title: 'Блок B — going to (планы)',
        points: [
          'am/is/are + going to + V — план / намерение',
          "I'm going to visit a museum.",
          "She isn't going to work tomorrow.",
        ],
        examples: [
          'I am going to stay at home tomorrow.',
          'We are going to buy tickets.',
        ],
      },
      {
        type: 'drill',
        id: 'e8',
        prompt: 'I ___ going to travel next week.',
        options: ['am', 'is', 'are'],
        answer: 'am',
      },
      {
        type: 'builder',
        id: 'e9',
        prompt: 'План на завтра',
        tokens: ['I', 'am', 'going', 'to', 'buy', 'a', 'ticket', 'tomorrow', '.'],
        answer: ['I', 'am', 'going', 'to', 'buy', 'a', 'ticket', 'tomorrow', '.'],
      },
      {
        type: 'explain',
        id: 'e10',
        title: "Блок C — I'd like (желание)",
        points: [
          "I'd like = I would like — вежливое «я бы хотел(а)»",
          "I'd like a quiet weekend. / I'd like some tea.",
          'Рядом: want / need — I want rest. I need a ticket.',
        ],
        examples: [
          "I'd like a coffee, please.",
          "I'd like to stay at home.",
        ],
      },
      {
        type: 'drill',
        id: 'e11',
        prompt: "___ like a coffee, please.",
        options: ["I'd", 'I am', 'I did'],
        answer: "I'd",
      },
      {
        type: 'dialogue',
        id: 'e12',
        title: 'Weekend talk',
        lines: [
          { id: 'd1', speaker: 'Sam', text: 'Did you have fun last weekend?' },
          {
            id: 'd2',
            speaker: 'You',
            choices: [
              { text: 'Yes, I did. I went to a museum.', correct: true },
              { text: 'Yes, I went. I did went to a museum.', correct: false },
            ],
          },
          { id: 'd3', speaker: 'Sam', text: 'What are you going to do next weekend?' },
          {
            id: 'd4',
            speaker: 'You',
            choices: [
              {
                text: "I'm going to stay at home. I'd like a quiet day.",
                correct: true,
              },
              {
                text: 'I going stay home. I like quiet day yesterday.',
                correct: false,
              },
            ],
          },
        ],
      },
      {
        type: 'cloze',
        id: 'e13',
        text:
          'Last Sunday Anna ___ to the centre. She ___ a ticket and ___ a film. In the evening she ___ tired but happy.',
        gaps: [
          { id: 'g1', answer: 'went', options: ['went', 'go', 'goes'] },
          { id: 'g2', answer: 'bought', options: ['bought', 'buy', 'buys'] },
          { id: 'g3', answer: 'saw', options: ['saw', 'see', 'seen'] },
          { id: 'g4', answer: 'was', options: ['was', 'were', 'is'] },
        ],
      },
      {
        type: 'cards',
        id: 'e14',
        cards: [
          { id: 'u6c25', term: 'tomorrow', translation: 'завтра', example: 'See you tomorrow.' },
          { id: 'u6c26', term: 'next week', translation: 'на следующей неделе', example: 'Next week I am free.' },
          { id: 'u6c27', term: 'plan', translation: 'план', example: 'I have a plan.' },
          { id: 'u6c28', term: 'trip', translation: 'поездка', example: 'A short trip.' },
          { id: 'u6c29', term: 'enjoy', translation: 'получать удовольствие', example: 'Did you enjoy it?' },
          { id: 'u6c30', term: 'fun', translation: 'веселье / забавно', example: 'It was fun.' },
          { id: 'u6c31', term: 'hungry', translation: 'голодный', example: 'I am hungry.' },
          { id: 'u6c32', term: "I'd like", translation: 'я бы хотел(а)', example: "I'd like some tea." },
        ],
      },
      {
        type: 'produce',
        id: 'e15',
        prompt: 'Level 1 Challenge',
        promptRu:
          'Level Challenge: A) My last weekend (6 предложений с Past / Did). B) My plans for next weekend (4 предложения с going to / I\'d like).',
        hints: [
          'Last weekend I…',
          "I didn't…",
          'I am going to…',
          "I'd like…",
        ],
        minSentences: 10,
      },
    ],
  },
}
