import type { LessonContent } from '../../types'

export const lessonContents: Record<string, LessonContent> = {
  'l1-u5-l1': {
    lessonId: 'l1-u5-l1',
    durationMin: 35,
    exercises: [
      {
        type: 'explain',
        id: 'e1',
        title: 'Prepositions of place',
        points: [
          'in — в (комнате, сумке, городе): in the bag',
          'on — на поверхности: on the desk / on the wall',
          'at — у точки: at the entrance, at the station',
          'next to, between, behind, in front of, under, near',
        ],
        examples: [
          'My phone is in my pocket.',
          'The keys are on the table.',
          'The hotel is next to the station.',
        ],
      },
      {
        type: 'drill',
        id: 'e2',
        prompt: 'The book is ___ the shelf.',
        options: ['on', 'in', 'at'],
        answer: 'on',
      },
      {
        type: 'drill',
        id: 'e3',
        prompt: 'I am ___ the entrance.',
        options: ['at', 'on', 'under'],
        answer: 'at',
      },
      {
        type: 'drill',
        id: 'e4',
        prompt: 'The cat is ___ the sofa. (под)',
        options: ['under', 'between', 'on'],
        answer: 'under',
      },
      {
        type: 'drill',
        id: 'e5',
        prompt: 'The shop is ___ the bank and the café.',
        options: ['between', 'behind', 'in'],
        answer: 'between',
      },
      {
        type: 'builder',
        id: 'e6',
        prompt: 'Travel seed',
        tokens: ['The', 'hotel', 'is', 'next', 'to', 'the', 'station', '.'],
        answer: ['The', 'hotel', 'is', 'next', 'to', 'the', 'station', '.'],
      },
      {
        type: 'cloze',
        id: 'e7',
        text: 'My bag is ___ the chair. The exit is ___ the right.',
        gaps: [
          { id: 'g1', answer: 'under', options: ['under', 'at', 'between'] },
          { id: 'g2', answer: 'on', options: ['on', 'in', 'at'] },
        ],
      },
      {
        type: 'cards',
        id: 'e8',
        cards: [
          { id: 'u5c1', term: 'next to', translation: 'рядом с', example: 'Next to the desk.' },
          { id: 'u5c2', term: 'between', translation: 'между', example: 'Between two buildings.' },
          { id: 'u5c3', term: 'behind', translation: 'за / позади', example: 'Behind the door.' },
          { id: 'u5c4', term: 'in front of', translation: 'перед', example: 'In front of the exit.' },
          { id: 'u5c5', term: 'entrance', translation: 'вход', example: 'At the entrance.' },
          { id: 'u5c6', term: 'exit', translation: 'выход', example: 'Where is the exit?' },
          { id: 'u5c7', term: 'bridge', translation: 'мост', example: 'Near the bridge.' },
          { id: 'u5c8', term: 'square', translation: 'площадь', example: 'In the square.' },
        ],
      },
      {
        type: 'produce',
        id: 'e9',
        prompt: 'Where are my things?',
        promptRu: 'Где лежат 5 вещей в комнате? Используйте in/on/at/under/next to…',
        hints: ['My phone is…', 'The keys are…', 'on / in / under / next to'],
        minSentences: 5,
      },
    ],
  },

  'l1-u5-l2': {
    lessonId: 'l1-u5-l2',
    durationMin: 35,
    exercises: [
      {
        type: 'explain',
        id: 'e1',
        title: 'Prepositions of time: in / on / at',
        points: [
          'at + время / night / weekend (BrE): at 7, at night, at the weekend',
          'on + дни и даты: on Monday, on 3 May; AmE часто on the weekend',
          'in + части дня / месяцы / годы: in the morning, in July, in 2020',
          'at night (не in night)',
          'on holiday (BrE отпуск) — не in the holiday; AmE: on vacation',
        ],
        examples: [
          'See you on Saturday at 5.',
          'I work in the morning.',
          'We are on holiday in July.',
        ],
      },
      {
        type: 'drill',
        id: 'e2',
        prompt: 'I get up ___ 7 o\'clock.',
        options: ['at', 'on', 'in'],
        answer: 'at',
      },
      {
        type: 'drill',
        id: 'e3',
        prompt: 'We meet ___ Friday.',
        options: ['on', 'in', 'at'],
        answer: 'on',
      },
      {
        type: 'drill',
        id: 'e4',
        prompt: 'I sleep well ___ night.',
        options: ['at', 'in', 'on'],
        answer: 'at',
      },
      {
        type: 'drill',
        id: 'e5',
        prompt: 'My birthday is ___ January.',
        options: ['in', 'on', 'at'],
        answer: 'in',
      },
      {
        type: 'builder',
        id: 'e6',
        prompt: 'Appointment',
        tokens: ['I', 'have', 'a', 'meeting', 'on', 'Monday', 'at', '10', '.'],
        answer: ['I', 'have', 'a', 'meeting', 'on', 'Monday', 'at', '10', '.'],
      },
      {
        type: 'cloze',
        id: 'e7',
        text: 'Let\'s meet ___ the afternoon ___ Saturday.',
        gaps: [
          { id: 'g1', answer: 'in', options: ['in', 'on', 'at'] },
          { id: 'g2', answer: 'on', options: ['in', 'on', 'at'] },
        ],
      },
      {
        type: 'cards',
        id: 'e8',
        cards: [
          { id: 'u5c9', term: 'Monday', translation: 'понедельник', example: 'On Monday.' },
          { id: 'u5c10', term: 'birthday', translation: 'день рождения', example: 'My birthday is in May.' },
          {
            id: 'u5c11',
            term: 'on holiday',
            translation: 'в отпуске (BrE); праздник = public holiday',
            example: "I'm on holiday in July.",
          },
          { id: 'u5c12', term: 'noon', translation: 'полдень', example: 'At noon.' },
          { id: 'u5c13', term: 'midnight', translation: 'полночь', example: 'At midnight.' },
          { id: 'u5c14', term: 'appointment', translation: 'запись / встреча', example: 'I have an appointment.' },
          { id: 'u5c15', term: 'meeting', translation: 'совещание / встреча', example: 'A meeting at 3.' },
          { id: 'u5c16', term: 'date', translation: 'дата', example: 'What is the date?' },
        ],
      },
      {
        type: 'produce',
        id: 'e9',
        prompt: 'My week',
        promptRu: 'Расскажите о своей неделе: 6 предложений с in / on / at.',
        hints: ['on Monday…', 'at 8…', 'in the evening…'],
        minSentences: 6,
      },
    ],
  },

  'l1-u5-l3': {
    lessonId: 'l1-u5-l3',
    durationMin: 35,
    exercises: [
      {
        type: 'explain',
        id: 'e1',
        title: 'Present Continuous',
        points: [
          'am/is/are + V-ing — действие сейчас',
          "I am working. She is waiting. They aren't sleeping.",
          'Вопрос: Are you working? What is he doing?',
          'Слова-подсказки: now, at the moment, today (иногда)',
        ],
        examples: [
          'I am reading now.',
          'It is raining.',
          'What are you doing?',
        ],
      },
      {
        type: 'drill',
        id: 'e2',
        prompt: 'I ___ working now.',
        options: ['am', 'is', 'are'],
        answer: 'am',
      },
      {
        type: 'drill',
        id: 'e3',
        prompt: 'She ___ waiting for a taxi.',
        options: ['is', 'am', 'are'],
        answer: 'is',
      },
      {
        type: 'drill',
        id: 'e4',
        prompt: 'They ___ sitting outside.',
        options: ["aren't", "isn't", "am not"],
        answer: "aren't",
      },
      {
        type: 'drill',
        id: 'e5',
        prompt: '___ it raining?',
        options: ['Is', 'Are', 'Does'],
        answer: 'Is',
      },
      {
        type: 'builder',
        id: 'e6',
        prompt: 'Question',
        tokens: ['What', 'are', 'you', 'doing', '?'],
        answer: ['What', 'are', 'you', 'doing', '?'],
      },
      {
        type: 'cloze',
        id: 'e7',
        text: 'Look! He ___ a blue jacket. We ___ for the bus.',
        gaps: [
          { id: 'g1', answer: 'is wearing', options: ['is wearing', 'wears', 'wear'] },
          { id: 'g2', answer: 'are waiting', options: ['are waiting', 'wait', 'waits'] },
        ],
      },
      {
        type: 'cards',
        id: 'e8',
        cards: [
          { id: 'u5c17', term: 'right now', translation: 'прямо сейчас', example: 'I am busy right now.' },
          { id: 'u5c18', term: 'wear', translation: 'носить (одежду)', example: 'She is wearing a coat.' },
          { id: 'u5c19', term: 'wait', translation: 'ждать', example: 'We are waiting for the bus.' },
          { id: 'u5c20', term: 'sit', translation: 'сидеть', example: 'He is sitting outside.' },
          { id: 'u5c21', term: 'stand', translation: 'стоять', example: 'I am standing here.' },
          { id: 'u5c22', term: 'rain', translation: 'идти (о дожде)', example: 'It is raining.' },
          { id: 'u5c23', term: 'happen', translation: 'происходить', example: 'What is happening?' },
          { id: 'u5c24', term: 'talk', translation: 'говорить / разговаривать', example: 'They are talking.' },
        ],
      },
      {
        type: 'produce',
        id: 'e9',
        prompt: 'Picture now',
        promptRu: 'Опишите «картинку сейчас»: 6 предложений в Present Continuous.',
        hints: ['I am…', 'She is wearing…', 'It is raining…', 'They are…'],
        minSentences: 6,
      },
    ],
  },

  'l1-u5-l4': {
    lessonId: 'l1-u5-l4',
    durationMin: 40,
    exercises: [
      {
        type: 'explain',
        id: 'e1',
        title: 'Present Simple vs Continuous',
        points: [
          'Simple — привычки: I usually work at home.',
          'Continuous — сейчас: Today I am working in a café.',
          'Не путать: She lives in Rome (факт) ≠ She is living here this month (временно)',
          'always/usually → Simple; now/at the moment → Continuous',
        ],
        examples: [
          'I usually drink tea, but today I am drinking coffee.',
          'He works in a bank. Right now he is talking to a client.',
        ],
      },
      {
        type: 'drill',
        id: 'e2',
        prompt: 'I usually ___ to work.',
        options: ['walk', 'am walking', 'walking'],
        answer: 'walk',
      },
      {
        type: 'drill',
        id: 'e3',
        prompt: 'Quiet! The baby ___ .',
        options: ['is sleeping', 'sleeps', 'sleep'],
        answer: 'is sleeping',
      },
      {
        type: 'drill',
        id: 'e4',
        prompt: 'She ___ English every day.',
        options: ['studies', 'is studying', 'study'],
        answer: 'studies',
      },
      {
        type: 'drill',
        id: 'e5',
        prompt: 'Look! It ___ .',
        options: ['is raining', 'rains', 'rain'],
        answer: 'is raining',
      },
      {
        type: 'builder',
        id: 'e6',
        prompt: 'Contrast',
        tokens: ['Usually', 'I', 'cook', ',', 'but', 'today', 'I', 'am', 'eating', 'out', '.'],
        answer: ['Usually', 'I', 'cook', ',', 'but', 'today', 'I', 'am', 'eating', 'out', '.'],
      },
      {
        type: 'dialogue',
        id: 'e7',
        title: 'Strange day',
        lines: [
          { id: 'd1', speaker: 'Sam', text: 'What are you doing today?' },
          {
            id: 'd2',
            speaker: 'You',
            choices: [
              {
                text: 'Usually I work at home, but today I am working in a café.',
                correct: true,
              },
              {
                text: 'Usually I am work at home, but today I work in a café.',
                correct: false,
              },
            ],
          },
          { id: 'd3', speaker: 'Sam', text: 'Are you tired?' },
          {
            id: 'd4',
            speaker: 'You',
            choices: [
              { text: 'A bit. I am drinking coffee right now.', correct: true },
              { text: 'A bit. I drink coffee right now always.', correct: false },
            ],
          },
        ],
      },
      {
        type: 'cards',
        id: 'e8',
        cards: [
          { id: 'u5c25', term: 'at the moment', translation: 'в данный момент', example: 'I am busy at the moment.' },
          { id: 'u5c26', term: 'this week', translation: 'на этой неделе', example: 'I am working late this week.' },
          { id: 'u5c27', term: 'strange', translation: 'странный', example: 'A strange day.' },
          { id: 'u5c28', term: 'normal', translation: 'обычный', example: 'A normal morning.' },
          { id: 'u5c29', term: 'tired', translation: 'усталый', example: 'I am tired.' },
          { id: 'u5c30', term: 'right now', translation: 'прямо сейчас', example: 'Right now I am free.' },
          { id: 'u5c31', term: 'today', translation: 'сегодня', example: 'Today I am walking.' },
          { id: 'u5c32', term: 'usually', translation: 'обычно', example: 'I usually stay in.' },
        ],
      },
      {
        type: 'produce',
        id: 'e9',
        prompt: 'Unit Challenge',
        promptRu:
          'Unit Challenge: «Usually I… but today I am…» — 7 предложений, смешайте Simple и Continuous.',
        hints: ['Usually I…', 'but today I am…', 'Right now…', 'At the moment…'],
        minSentences: 7,
      },
    ],
  },
}
